package com.ilinklink.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.ilinklink.greendao.LoginModelDao;
import com.ilinklink.greendao.WifiModelDao;
import com.ilinklink.greendao.TrainingModelDao;
import com.ilinklink.greendao.StudentInfoDao;
import com.ilinklink.greendao.ExamInfoDao;
import com.ilinklink.greendao.StudentExamDao;
import com.ilinklink.greendao.ExamRecordDao;
import com.ilinklink.greendao.StudentExamRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 7): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 7;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        LoginModelDao.createTable(db, ifNotExists);
        WifiModelDao.createTable(db, ifNotExists);
        TrainingModelDao.createTable(db, ifNotExists);
        StudentInfoDao.createTable(db, ifNotExists);
        ExamInfoDao.createTable(db, ifNotExists);
        StudentExamDao.createTable(db, ifNotExists);
        ExamRecordDao.createTable(db, ifNotExists);
        StudentExamRecordDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        LoginModelDao.dropTable(db, ifExists);
        WifiModelDao.dropTable(db, ifExists);
        TrainingModelDao.dropTable(db, ifExists);
        StudentInfoDao.dropTable(db, ifExists);
        ExamInfoDao.dropTable(db, ifExists);
        StudentExamDao.dropTable(db, ifExists);
        ExamRecordDao.dropTable(db, ifExists);
        StudentExamRecordDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(LoginModelDao.class);
        registerDaoClass(WifiModelDao.class);
        registerDaoClass(TrainingModelDao.class);
        registerDaoClass(StudentInfoDao.class);
        registerDaoClass(ExamInfoDao.class);
        registerDaoClass(StudentExamDao.class);
        registerDaoClass(ExamRecordDao.class);
        registerDaoClass(StudentExamRecordDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
