package com.ilinklink.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXAM_INFO.
 */
public class ExamInfo {

    private Long id;
    private String examUUID;
    private String name;
    private String desc;
    private String remark;
    private Double difficultyThreshold;
    private Long limitTime;

    public ExamInfo() {
    }

    public ExamInfo(Long id) {
        this.id = id;
    }

    public ExamInfo(Long id, String examUUID, String name, String desc, String remark, Double difficultyThreshold, Long limitTime) {
        this.id = id;
        this.examUUID = examUUID;
        this.name = name;
        this.desc = desc;
        this.remark = remark;
        this.difficultyThreshold = difficultyThreshold;
        this.limitTime = limitTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExamUUID() {
        return examUUID;
    }

    public void setExamUUID(String examUUID) {
        this.examUUID = examUUID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Double getDifficultyThreshold() {
        return difficultyThreshold;
    }

    public void setDifficultyThreshold(Double difficultyThreshold) {
        this.difficultyThreshold = difficultyThreshold;
    }

    public Long getLimitTime() {
        return limitTime;
    }

    public void setLimitTime(Long limitTime) {
        this.limitTime = limitTime;
    }

}
