package com.ilinklink.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGIN_MODEL.
 */
public class LoginModel {

    private Long id;
    private Integer usrId;
    private Integer accId;
    private Integer accType;
    private Integer certificate;
    private String accAcount;
    private String tocken;
    private String usrName;
    private String usrImMobile;
    private String usrPictureUri;
    private String password;
    private String wx_open_id;
    private String weibo_open_id;
    private Long login_time;
    private Boolean is_logged;
    private String md5;
    private String uid;

    public LoginModel() {
    }

    public LoginModel(Long id) {
        this.id = id;
    }

    public LoginModel(Long id, Integer usrId, Integer accId, Integer accType, Integer certificate, String accAcount, String tocken, String usrName, String usrImMobile, String usrPictureUri, String password, String wx_open_id, String weibo_open_id, Long login_time, Boolean is_logged, String md5, String uid) {
        this.id = id;
        this.usrId = usrId;
        this.accId = accId;
        this.accType = accType;
        this.certificate = certificate;
        this.accAcount = accAcount;
        this.tocken = tocken;
        this.usrName = usrName;
        this.usrImMobile = usrImMobile;
        this.usrPictureUri = usrPictureUri;
        this.password = password;
        this.wx_open_id = wx_open_id;
        this.weibo_open_id = weibo_open_id;
        this.login_time = login_time;
        this.is_logged = is_logged;
        this.md5 = md5;
        this.uid = uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUsrId() {
        return usrId;
    }

    public void setUsrId(Integer usrId) {
        this.usrId = usrId;
    }

    public Integer getAccId() {
        return accId;
    }

    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    public Integer getAccType() {
        return accType;
    }

    public void setAccType(Integer accType) {
        this.accType = accType;
    }

    public Integer getCertificate() {
        return certificate;
    }

    public void setCertificate(Integer certificate) {
        this.certificate = certificate;
    }

    public String getAccAcount() {
        return accAcount;
    }

    public void setAccAcount(String accAcount) {
        this.accAcount = accAcount;
    }

    public String getTocken() {
        return tocken;
    }

    public void setTocken(String tocken) {
        this.tocken = tocken;
    }

    public String getUsrName() {
        return usrName;
    }

    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }

    public String getUsrImMobile() {
        return usrImMobile;
    }

    public void setUsrImMobile(String usrImMobile) {
        this.usrImMobile = usrImMobile;
    }

    public String getUsrPictureUri() {
        return usrPictureUri;
    }

    public void setUsrPictureUri(String usrPictureUri) {
        this.usrPictureUri = usrPictureUri;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getWx_open_id() {
        return wx_open_id;
    }

    public void setWx_open_id(String wx_open_id) {
        this.wx_open_id = wx_open_id;
    }

    public String getWeibo_open_id() {
        return weibo_open_id;
    }

    public void setWeibo_open_id(String weibo_open_id) {
        this.weibo_open_id = weibo_open_id;
    }

    public Long getLogin_time() {
        return login_time;
    }

    public void setLogin_time(Long login_time) {
        this.login_time = login_time;
    }

    public Boolean getIs_logged() {
        return is_logged;
    }

    public void setIs_logged(Boolean is_logged) {
        this.is_logged = is_logged;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

}
