package com.ilinklink.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT_EXAM.
 */
public class StudentExam {

    private Long id;
    private String examUUID;
    private String resultUUID;
    private String studentUUID;
    private String desc;

    public StudentExam() {
    }

    public StudentExam(Long id) {
        this.id = id;
    }

    public StudentExam(Long id, String examUUID, String resultUUID, String studentUUID, String desc) {
        this.id = id;
        this.examUUID = examUUID;
        this.resultUUID = resultUUID;
        this.studentUUID = studentUUID;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExamUUID() {
        return examUUID;
    }

    public void setExamUUID(String examUUID) {
        this.examUUID = examUUID;
    }

    public String getResultUUID() {
        return resultUUID;
    }

    public void setResultUUID(String resultUUID) {
        this.resultUUID = resultUUID;
    }

    public String getStudentUUID() {
        return studentUUID;
    }

    public void setStudentUUID(String studentUUID) {
        this.studentUUID = studentUUID;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
