package com.ilinklink.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ilinklink.greendao.StudentExam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STUDENT_EXAM.
*/
public class StudentExamDao extends AbstractDao<StudentExam, Long> {

    public static final String TABLENAME = "STUDENT_EXAM";

    /**
     * Properties of entity StudentExam.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ExamUUID = new Property(1, String.class, "examUUID", false, "EXAM_UUID");
        public final static Property ResultUUID = new Property(2, String.class, "resultUUID", false, "RESULT_UUID");
        public final static Property StudentUUID = new Property(3, String.class, "studentUUID", false, "STUDENT_UUID");
        public final static Property Desc = new Property(4, String.class, "desc", false, "DESC");
    };


    public StudentExamDao(DaoConfig config) {
        super(config);
    }
    
    public StudentExamDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'STUDENT_EXAM' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'EXAM_UUID' TEXT," + // 1: examUUID
                "'RESULT_UUID' TEXT," + // 2: resultUUID
                "'STUDENT_UUID' TEXT," + // 3: studentUUID
                "'DESC' TEXT);"); // 4: desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STUDENT_EXAM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StudentExam entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String examUUID = entity.getExamUUID();
        if (examUUID != null) {
            stmt.bindString(2, examUUID);
        }
 
        String resultUUID = entity.getResultUUID();
        if (resultUUID != null) {
            stmt.bindString(3, resultUUID);
        }
 
        String studentUUID = entity.getStudentUUID();
        if (studentUUID != null) {
            stmt.bindString(4, studentUUID);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(5, desc);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public StudentExam readEntity(Cursor cursor, int offset) {
        StudentExam entity = new StudentExam( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // examUUID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // resultUUID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // studentUUID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // desc
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StudentExam entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setExamUUID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setResultUUID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStudentUUID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDesc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(StudentExam entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(StudentExam entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
