package com.ilinklink.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRAINING_MODEL.
 */
public class TrainingModel {

    private Long id;
    private String trainingId;
    private String courseId;
    private String groupId;
    private Integer groupIndex;
    private String frameId;
    private Long frameIndex;
    private Long frameTime;
    private byte[] frameContent;
    private Float frameMatchDegreet;
    private String userAcount;
    private String userId;
    private String actionId;
    private String sign;
    private Long time;

    public TrainingModel() {
    }

    public TrainingModel(Long id) {
        this.id = id;
    }

    public TrainingModel(Long id, String trainingId, String courseId, String groupId, Integer groupIndex, String frameId, Long frameIndex, Long frameTime, byte[] frameContent, Float frameMatchDegreet, String userAcount, String userId, String actionId, String sign, Long time) {
        this.id = id;
        this.trainingId = trainingId;
        this.courseId = courseId;
        this.groupId = groupId;
        this.groupIndex = groupIndex;
        this.frameId = frameId;
        this.frameIndex = frameIndex;
        this.frameTime = frameTime;
        this.frameContent = frameContent;
        this.frameMatchDegreet = frameMatchDegreet;
        this.userAcount = userAcount;
        this.userId = userId;
        this.actionId = actionId;
        this.sign = sign;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTrainingId() {
        return trainingId;
    }

    public void setTrainingId(String trainingId) {
        this.trainingId = trainingId;
    }

    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Integer getGroupIndex() {
        return groupIndex;
    }

    public void setGroupIndex(Integer groupIndex) {
        this.groupIndex = groupIndex;
    }

    public String getFrameId() {
        return frameId;
    }

    public void setFrameId(String frameId) {
        this.frameId = frameId;
    }

    public Long getFrameIndex() {
        return frameIndex;
    }

    public void setFrameIndex(Long frameIndex) {
        this.frameIndex = frameIndex;
    }

    public Long getFrameTime() {
        return frameTime;
    }

    public void setFrameTime(Long frameTime) {
        this.frameTime = frameTime;
    }

    public byte[] getFrameContent() {
        return frameContent;
    }

    public void setFrameContent(byte[] frameContent) {
        this.frameContent = frameContent;
    }

    public Float getFrameMatchDegreet() {
        return frameMatchDegreet;
    }

    public void setFrameMatchDegreet(Float frameMatchDegreet) {
        this.frameMatchDegreet = frameMatchDegreet;
    }

    public String getUserAcount() {
        return userAcount;
    }

    public void setUserAcount(String userAcount) {
        this.userAcount = userAcount;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getActionId() {
        return actionId;
    }

    public void setActionId(String actionId) {
        this.actionId = actionId;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
