package com.ilinklink.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WIFI_MODEL.
 */
public class WifiModel {

    private Long id;
    private String wifiName;
    private String wifiPassword;
    private String capabilities;

    public WifiModel() {
    }

    public WifiModel(Long id) {
        this.id = id;
    }

    public WifiModel(Long id, String wifiName, String wifiPassword, String capabilities) {
        this.id = id;
        this.wifiName = wifiName;
        this.wifiPassword = wifiPassword;
        this.capabilities = capabilities;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWifiName() {
        return wifiName;
    }

    public void setWifiName(String wifiName) {
        this.wifiName = wifiName;
    }

    public String getWifiPassword() {
        return wifiPassword;
    }

    public void setWifiPassword(String wifiPassword) {
        this.wifiPassword = wifiPassword;
    }

    public String getCapabilities() {
        return capabilities;
    }

    public void setCapabilities(String capabilities) {
        this.capabilities = capabilities;
    }

}
